theme: minima
title: brauner's blog
author: Christian Brauner
description: > # this means to ignore newlines until "twitter_username:"
  My Linux kernel contributions are made using the following email addresses
  (Simply search for them in the Linux kernel git logs.):
  christian(at)brauner(dot)io
  christian.brauner(at)ubuntu(dot)com
  https://git.kernel.org/pub/scm/linux/kernel/git/brauner/linux.git/
google_analytics: UA-114731872-1
timezone: Europe/Berlin
freenode_username: brauner
twitter_username: brau_ner
github_username: brauner
facebook_username: freiherrgarbage
instagram_username: brau_ner
linkedin_username: christian-brauner-586185110
show_excerpts: false
disqus:
  shortname: https-brauner-github-io
plugins:
  - jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
include:
  - "_img"
