theme: minima
title: brauner's blog
author: Christian Brauner
google_analytics: UA-114731872-1
timezone: Europe/Berlin
twitter_username: brau_ner
github_username: brauner
facebook_username: freiherrgarbage
instagram_username: brau_ner
linkedin_username: christian-brauner-586185110
show_excerpts: false
disqus:
  shortname: https-brauner-github-io
plugins:
  - jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
include:
  - "_img"
