theme: minima
title: Personal blog of Christian Brauner
author:
  name: Christian Brauner
url: "https://brauner.io"
timezone: Europe/Berlin
show_excerpts: false
disqus:
  shortname: https-brauner-github-io
plugins:
  - jekyll-feed
  - jekyll-remote-theme
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
include:
  - "_img"
